### ISSUE TITLE
regression: $store is undefined for arbitrary functions

### ISSUE THREAD

**Issue by chapmanjacobd** [ryangjchandler/spruce#68] opened 2020-10-18 15:16 UTC
test case: works w/ 0.x.x but not with 1.x or 2.x

compare.html in https://github.com/chapmanjacobd/neighborhoods-alpinejs

**Comment by ryangjchandler** [comment] 2020-10-18 15:36
Will need to investigate this one more deeply to see what the problem is, whether it's Alpine being weird or Spruce, but for now on newer versions you should be able to pass the `$store` variable through to the function: 

```html
x-on:click="functionName($store)"
```

**Comment by robbevp** [comment] 2020-10-19 14:21
Same here: $store is unavailable in my reuseable components.
Calling `x-show="status($store)"` fixed this

**Comment by ryangjchandler** [comment] 2020-10-19 14:26
@robbevp Is the `status` function defined outside of the component, meaning it's not a function on the `x-data` object?

**Comment by robbevp** [comment] 2020-10-19 14:35
@ryangjchandler 
If I understand you correctly it is not.
In my view I have something like this
``` html
<div x-data="card({id: 3})>
  <p x-show="status($store)">
    active
  </p>
</div>
```
In the JS:
``` javascript```
export function card(data) {
  return {
    ...data,
    status($store) {
      return this.id === $store.events.current_id;
      }
  }
}

```

**Comment by ryangjchandler** [comment] 2020-10-19 14:42
That's exactly what I mean. Inside of those sort of functions (where you have defined the function on the data object), you need to use `this.$store` instead of just `$store`, or pass the variable through like you have done.

**Comment by ryangjchandler** [comment] 2020-10-20 10:47
I'm not sure there's actually a way to fix this within Spruce, it's more to do with the behaviour of Alpine and how it binds to the `this` context of a function.

The simplest way of working around it is by using the `Spruce.store('name')` approach to get the store, instead of `$store.name`. Modifications made this way will still trigger a render.

So, instead of doing something like `$store.name.first = 'Ryan'`, you could do `Spruce.store('name').first = 'Ryan'`.

The correct way of using `this.$store` would be adding the function to the data object, that way Alpine will bind correctly to `this`.

I'm going to close this issue and mark as _wontfix_, but if anybody can think of any other solutions that don't involve doing `nameOfFunction.bind(this)` or something nasty, please comment below.

**Closed by ryangjchandler** 2020-10-20 10:47 UTC
