### ISSUE TITLE
Have a problem with @click.away

### ISSUE THREAD

**Issue by phijma** [ryangjchandler/spruce#135] opened 2021-02-25 16:49 UTC
Before using Spruce, this worked fine:

```
<div x-cloak x-show="isModalOpen()">
    <div></div> -> this is a full screen background with opacity
    <div @click.away="closeModal()"></div> -> actual modal/dialog
</div>
```

Now with Spruce I've got this:

```
<div x-data x-cloak x-show="$store.modal.isOpen()" >
    <div></div> -> this is a full screen background with opacity
    <div @click.away="$store.modal.close()"></div> -> actual modal/dialog
</div>
```

The problem is. As soon as I open the modal, this `$store.modal.close()` runs, closing the modal and therefore not showing up at all.

**Comment by ryangjchandler** [comment] 2021-02-25 18:44
@phijma Please try and re-produce in a CodePen / JSFiddle.

**Comment by phijma** [comment] 2021-02-25 18:57
@ryangjchandler here you go: https://codepen.io/phijma/pen/KKNZOpV

**Comment by ryangjchandler** [comment] 2021-02-25 19:09
@phijma To be completely honest, I don't think this is a bug. When you click the button, you are _actually_ clicking outside of the `<p>` tag so it should be calling the `close` function.

**Comment by phijma** [comment] 2021-02-25 19:10
So it's the other method that is a bug?

**Comment by ryangjchandler** [comment] 2021-02-25 19:11
> So it's the other method that is a bug?

I guess so - Alpine should probably be behaving differently to how it is.

**Comment by phijma** [comment] 2021-02-25 19:13
> > So it's the other method that is a bug?
> 
> I guess so - Alpine should probably be behaving differently to how it is.

Alright, in that case: this issue can be closed. Thanks!

**Comment by phijma** [comment] 2021-02-25 19:16
BTW @ryangjchandler. Do you know a way in which I could do this correctly?

**Comment by phijma** [comment] 2021-02-25 20:37
Last question. Same behavior with ‘<template x-if...>’ instead of ‘<div x-show...>’. Is that expected as well?

**Comment by ryangjchandler** [comment] 2021-02-25 20:38
> Last question. Same behavior with ‘’ instead of ‘
> 
> ’. Is that expected as well?

Not sure what you mean..

**Comment by phijma** [comment] 2021-02-25 20:39
> > Last question. Same behavior with ‘’ instead of ‘
> > ’. Is that expected as well?
> 
> Not sure what you mean..

Edited.

**Comment by phijma** [comment] 2021-02-25 21:50
@ryangjchandler FYI: https://github.com/alpinejs/alpine/issues/1132#issuecomment-786249320

**Comment by phijma** [comment] 2021-02-26 08:09
I’ve reopened the issue. As I’m pretty convinced this is not expected behavior. It would be nice if one could expect the same behavior from vanilla Alpine and Spruce. 

Please close this once and for all if you don’t agree :-)

I think Spruce will make the element show up (x-show) **immediately** where vanilla alpine does not. As I’m not familiar with the internals it’s just a guess.

**Comment by ryangjchandler** [comment] 2021-03-01 15:30
@phijma I'll try to take a look at this later this week, time is a bit tight this week, sorry!

**Comment by phijma** [comment] 2021-03-01 16:13
If I can help somehow, let me know.

**Comment by ryangjchandler** [comment] 2021-03-01 16:20
@phijma You are right - I forget that Alpine uses a `show` stack so the changes aren't necessarily instantaneous. When you click the button and trigger a Spruce update however, Spruce will instantly ping the Alpine component and cause it to re-render before the `@click.away` handler runs, therefore showing the element.

Not sure what the best way to handle this would be... I'll need to experiment with a reproduction myself.

**Comment by phijma** [comment] 2021-03-01 18:54
> @phijma You are right - I forget that Alpine uses a `show` stack so the changes aren't necessarily instantaneous. When you click the button and trigger a Spruce update however, Spruce will instantly ping the Alpine component and cause it to re-render before the `@click.away` handler runs, therefore showing the element.
> 
> Not sure what the best way to handle this would be... I'll need to experiment with a reproduction myself.
> 
> For now, you could try and use a `setTimeout`:
> 
> ```js
> setTimeout(() => {
>     this.show = true
> }, 0)
> ```
> 
> That way, the update will run on the next tick presumably after the `@click.away` handler has run - can't be certain of this though.

I've already found another way of hacking around it. The reason to create this issue nonetheless is for clean and predictable code :)

**Comment by ryangjchandler** [comment] 2021-03-09 19:53
@phijma I'm going to close this because I don't actually think there's anyway of sorting this inside of Spruce. The problem is the fact that Spruce isn't as tightly coupled with Alpine as I'd like it to be, so I can't hook into any of the `showStack` related logic.

Hopefully this can be resolved with the release of Alpine and Spruce v3 in the near future.

**Closed by ryangjchandler** 2021-03-09 19:53 UTC
Labels: bug
